package cortex

// ─────────────────────────────────────────────────────────────────────
// Provenance — which module produced the last Process() answer
// ─────────────────────────────────────────────────────────────────────
//
// Organism.Process() fans out across many subsystems (fast-path caches,
// deterministic Tools, hippocampal recall, several generative fallbacks)
// and until now returned only the final text — an outside observer could
// not tell whether a reply was an exact calculator result, a recalled
// fact, or a hallucinated generation. Provenance closes that gap without
// changing Process()'s signature: Organism records what happened on the
// most recent call and exposes it via LastProvenance().

// ProvenanceSource identifies which module of the organism produced a
// Process() answer. Kept as a small, fixed set of typed constants so
// callers can switch on it exhaustively.
type ProvenanceSource string

const (
	// SourceTool means a registered Tool (cortex/tools.go, e.g. the
	// biomed organ, datetime, unit conversion, sqrt/pow) matched and
	// answered deterministically. Provenance.Tool names it.
	SourceTool ProvenanceSource = "tool"

	// SourceReasoning means one of ReasoningEngine's hardcoded skills
	// (arithmetic, word problems, sequences, syllogisms, sorting)
	// answered — deterministic, but not a pluggable Tool with a name.
	SourceReasoning ProvenanceSource = "reasoning"

	// SourceMemory means the answer was recalled rather than generated:
	// a Hippocampus SDR/keyword match, or a Cerebellum fast-path cache
	// hit replaying a previously confident answer.
	SourceMemory ProvenanceSource = "memory"

	// SourceBroca means the answer was freshly generated by a language
	// generation path (Transformer/Broca 2.0, FractalCortex, RadioCortex,
	// or the associative Broca 1.0 chain walker), optionally nudged by
	// the CognitiveBridge (see Provenance.Biased).
	SourceBroca ProvenanceSource = "broca"

	// SourceNone means nothing in the pipeline produced a confident
	// answer; the organism returned its canned NoConfidentResponse.
	SourceNone ProvenanceSource = "none"
)

// Provenance records which module answered the most recent Process()
// call. It is intentionally small and additive: existing callers that
// only use Process()'s string return value are unaffected.
type Provenance struct {
	// Source is which subsystem produced the answer.
	Source ProvenanceSource

	// Tool is the registered Tool's name (ToolRegistry.Dispatch's
	// toolName) when Source == SourceTool. Empty otherwise.
	Tool string

	// Recalled is the number of stored records (Hippocampus memory or
	// Cerebellum cache entry) that backed this answer. 0 when the
	// answer was not recalled from a store (tool/reasoning/broca/none).
	Recalled int

	// Biased is true when the CognitiveBridge injected a non-empty
	// logit bias (derived from episodic/semantic recall) into the
	// generation that produced this answer.
	Biased bool
}

// LastProvenance returns provenance for the most recent Process() call.
// Safe to call at any time; returns the zero Provenance before the first
// Process() call.
func (o *Organism) LastProvenance() Provenance {
	return o.provenance
}
