package componentspec

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"unicode"
)

// GoSource generates deterministic DTO definitions for record declarations.
// Generated code contains data shapes only; authority and execution remain in
// the owning runtime.
func (m Manifest) GoSource(packageName string) ([]byte, error) {
	if err := m.Validate(); err != nil {
		return nil, err
	}
	if !validGoIdentifier(packageName) {
		return nil, fmt.Errorf("invalid Go package name %q", packageName)
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by Swyp component go. DO NOT EDIT.\n")
	b.WriteString("// Source of truth: the corresponding .swyp component specification.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", packageName)

	records := 0
	for _, d := range m.Declarations {
		if d.Kind != "record" {
			continue
		}
		records++
		if !validGoExportedIdentifier(d.Name) {
			return nil, fmt.Errorf("record %q is not a valid exported Go type name", d.Name)
		}
		fmt.Fprintf(&b, "type %s struct {\n", d.Name)
		seenGoNames := map[string]string{}
		for _, f := range d.Fields {
			goName := exportedFieldName(f.Name)
			if goName == "" || !validGoExportedIdentifier(goName) {
				return nil, fmt.Errorf("record %s field %q cannot be represented as an exported Go identifier", d.Name, f.Name)
			}
			if previous, exists := seenGoNames[goName]; exists {
				return nil, fmt.Errorf("record %s fields %q and %q collide as Go field %s", d.Name, previous, f.Name, goName)
			}
			seenGoNames[goName] = f.Name
			goType, err := goTypeForRecordType(f.Type)
			if err != nil {
				return nil, fmt.Errorf("record %s field %s: %w", d.Name, f.Name, err)
			}
			fmt.Fprintf(&b, "\t%s %s `json:\"%s\"`\n", goName, goType, f.Name)
		}
		b.WriteString("}\n\n")
	}
	if records == 0 {
		return nil, fmt.Errorf("component source contains no record declarations")
	}

	raw := bytes.TrimRight(b.Bytes(), "\n")
	raw = append(raw, '\n')
	formatted, err := format.Source(raw)
	if err != nil {
		return nil, fmt.Errorf("format generated Go: %w", err)
	}
	formatted = bytes.TrimRight(formatted, "\n")
	formatted = append(formatted, '\n')
	return formatted, nil
}

func goTypeForRecordType(t string) (string, error) {
	switch t {
	case "string":
		return "string", nil
	case "bool":
		return "bool", nil
	case "i64":
		return "int64", nil
	case "u64":
		return "uint64", nil
	case "bytes":
		return "[]byte", nil
	case "string_list":
		return "[]string", nil
	case "string_map":
		return "map[string]string", nil
	default:
		return "", fmt.Errorf("unsupported record type %q", t)
	}
}

func exportedFieldName(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '_' || r == '-'
	})
	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		if initialism, ok := goInitialisms[strings.ToLower(part)]; ok {
			b.WriteString(initialism)
			continue
		}
		runes := []rune(part)
		runes[0] = unicode.ToUpper(runes[0])
		b.WriteString(string(runes))
	}
	return b.String()
}

var goInitialisms = map[string]string{
	"api":   "API",
	"cpu":   "CPU",
	"gb":    "GB",
	"gc":    "GC",
	"gpu":   "GPU",
	"http":  "HTTP",
	"https": "HTTPS",
	"id":    "ID",
	"ids":   "IDs",
	"ip":    "IP",
	"json":  "JSON",
	"kb":    "KB",
	"mb":    "MB",
	"ms":    "MS",
	"npu":   "NPU",
	"p2p":   "P2P",
	"ppm":   "PPM",
	"ram":   "RAM",
	"sha":   "SHA",
	"tcp":   "TCP",
	"udp":   "UDP",
	"ui":    "UI",
	"url":   "URL",
	"uuid":  "UUID",
	"vram":  "VRAM",
}

func validGoIdentifier(name string) bool {
	if name == "" {
		return false
	}
	for i, r := range name {
		if r != '_' && !unicode.IsLetter(r) && !(i > 0 && unicode.IsDigit(r)) {
			return false
		}
	}
	return true
}

func validGoExportedIdentifier(name string) bool {
	if !validGoIdentifier(name) {
		return false
	}
	first, _ := utf8FirstRune(name)
	return unicode.IsUpper(first)
}

func utf8FirstRune(s string) (rune, int) {
	for _, r := range s {
		return r, len(string(r))
	}
	return 0, 0
}
