package search
import("context";"crypto/sha256";"encoding/hex";"encoding/xml";"fmt";"io";"net";"net/http";"net/netip";"net/url";"regexp";"strings";"time";"unicode/utf8")
const UserAgent="SwypikBot/0.1"
type CrawlReport struct{Fetched int `json:"fetched"`;Indexed int `json:"indexed"`;Skipped int `json:"skipped"`;Errors []string `json:"errors"`}
func canonical(raw string)(string,error){if len(raw)>2048{return "",fmt.Errorf("URL too long")};u,err:=url.Parse(raw);if err!=nil||u.Hostname()==""||u.User!=nil||(u.Scheme!="http"&&u.Scheme!="https")||strings.Contains(u.Hostname(),"%"){return "",fmt.Errorf("absolute HTTP(S) URL required")};if u.Port()!=""&&u.Port()!="443"&&u.Port()!="80"{return "",fmt.Errorf("only standard web ports are allowed")};u.Scheme=strings.ToLower(u.Scheme);u.Host=strings.ToLower(u.Host);u.Fragment="";if u.Path==""{u.Path="/"};return u.String(),nil}
var blocked=[]string{"0.0.0.0/8","100.64.0.0/10","192.0.0.0/24","192.0.2.0/24","198.18.0.0/15","198.51.100.0/24","203.0.113.0/24","240.0.0.0/4","2001:db8::/32","2001::/32","2002::/16","64:ff9b::/96"}
func publicAddress(ip netip.Addr)bool{ip=ip.Unmap();if !ip.IsValid()||!ip.IsGlobalUnicast()||ip.IsPrivate()||ip.IsLoopback()||ip.IsLinkLocalUnicast(){return false};for _,s:=range blocked{if netip.MustParsePrefix(s).Contains(ip){return false}};return true}
func safeDial(ctx context.Context,network,address string)(net.Conn,error){host,port,err:=net.SplitHostPort(address);if err!=nil{return nil,err};ips,err:=net.DefaultResolver.LookupNetIP(ctx,"ip",host);if err!=nil{return nil,err};if len(ips)==0{return nil,fmt.Errorf("DNS returned no addresses")};for _,ip:=range ips{if !publicAddress(ip){return nil,fmt.Errorf("non-public destination blocked")}};var last error;for _,ip:=range ips{conn,err:=(&net.Dialer{Timeout:5*time.Second}).DialContext(ctx,network,net.JoinHostPort(ip.String(),port));if err==nil{return conn,nil};last=err};return nil,last}
func(e *Engine)Crawl(ctx context.Context,seed string,limit int)(CrawlReport,error){transport:=http.DefaultTransport.(*http.Transport).Clone();transport.Proxy=nil;transport.DialContext=safeDial;transport.MaxConnsPerHost=1;defer transport.CloseIdleConnections();client:=&http.Client{Transport:transport,Timeout:12*time.Second,CheckRedirect:func(*http.Request,[]*http.Request)error{return http.ErrUseLastResponse}};return e.crawl(ctx,seed,limit,client,time.Second)}
// Same-origin, sequential, explicit-seed crawl. No scripts, forms, cookies,
// credentials, external search providers or automatic background crawl.
func(e *Engine)crawl(ctx context.Context,seed string,limit int,client *http.Client,delay time.Duration)(CrawlReport,error){
 report:=CrawlReport{Errors:[]string{}};if limit<1||limit>32{return report,fmt.Errorf("page limit must be 1-32")};seed,err:=canonical(seed);if err!=nil{return report,err};u,_:=url.Parse(seed);origin:=u.Scheme+"://"+u.Host;if !e.crawlMu.TryLock(){return report,fmt.Errorf("a crawl is already running")};defer e.crawlMu.Unlock();ctx,cancel:=context.WithTimeout(ctx,2*time.Minute);defer cancel()
 fetch:=func(raw string,max int)([]byte,int,http.Header,error){select{case<-ctx.Done():return nil,0,nil,ctx.Err();case<-time.After(delay):};req,err:=http.NewRequestWithContext(ctx,"GET",raw,nil);if err!=nil{return nil,0,nil,err};req.Header.Set("User-Agent",UserAgent);req.Header.Set("Accept","text/html,text/plain;q=0.9");res,err:=client.Do(req);if err!=nil{return nil,0,nil,err};defer res.Body.Close();b,err:=io.ReadAll(io.LimitReader(res.Body,int64(max)+1));if len(b)>max{return nil,0,nil,fmt.Errorf("response exceeds byte limit")};return b,res.StatusCode,res.Header,err}
 // Conservative robots policy: only 404/410 count as absent. Errors and robots
 // redirects stop this crawl rather than bypassing site controls.
 b,status,_,err:=fetch(origin+"/robots.txt",512*1024);if err!=nil{return report,fmt.Errorf("robots unavailable: %w",err)};if status!=200&&status!=404&&status!=410{return report,fmt.Errorf("robots HTTP %d: crawl stopped",status)};policy:=robots{};if status==200{policy=parseRobots(string(b))};queue:=[]string{seed};visited:=map[string]bool{}
 for len(queue)>0&&report.Fetched<limit&&len(visited)<128{
  if err:=ctx.Err();err!=nil{return report,err};raw:=queue[0];queue=queue[1:];if visited[raw]{continue};visited[raw]=true;pageURL,_:=url.Parse(raw);path:=pageURL.EscapedPath();if pageURL.RawQuery!=""{path+="?"+pageURL.RawQuery};if !policy.allowed(path){report.Skipped++;if err:=e.Delete(raw);err!=nil{return report,err};continue}
  body,code,headers,err:=fetch(raw,1<<20);report.Fetched++;if err!=nil{report.Errors=append(report.Errors,raw+": fetch failed");continue}
  if code>=300&&code<400{next,err:=pageURL.Parse(headers.Get("Location"));if err==nil&&headers.Get("Location")!=""&&next.Scheme+"://"+next.Host==origin{if normalized,err:=canonical(next.String());err==nil{queue=append(queue,normalized)}};report.Skipped++;continue}
  if code!=200{report.Skipped++;if code==404||code==410{if err:=e.Delete(raw);err!=nil{return report,err}};continue};kind:=strings.ToLower(headers.Get("Content-Type"));if !strings.Contains(kind,"text/html")||!utf8.Valid(body){report.Skipped++;continue}
  title,text,links,noindex,nofollow,err:=extract(string(body));directive:=strings.ToLower(headers.Get("X-Robots-Tag"));noindex=noindex||strings.Contains(directive,"noindex")||strings.Contains(directive,"none");nofollow=nofollow||strings.Contains(directive,"nofollow")||strings.Contains(directive,"none");if err!=nil{report.Errors=append(report.Errors,raw+": unsupported HTML");continue}
  if noindex{report.Skipped++;if err:=e.Delete(raw);err!=nil{return report,err}}else if text!=""{if title==""{title=pageURL.Hostname()};digest:=sha256.Sum256(body);if err:=e.Upsert(Document{URL:raw,Title:clip(title,512),Text:clip(text,MaxTextBytes),FetchedAt:time.Now().UTC(),SHA256:hex.EncodeToString(digest[:])});err!=nil{return report,err};report.Indexed++}
  if !nofollow{for _,link:=range links{next,err:=pageURL.Parse(link);if err!=nil||next.Scheme+"://"+next.Host!=origin{continue};normalized,err:=canonical(next.String());if err==nil&&!visited[normalized]&&len(queue)<128{queue=append(queue,normalized)}}}
 };return report,ctx.Err()
}
func clip(s string,n int)string{if len(s)<=n{return s};s=s[:n];for !utf8.ValidString(s){s=s[:len(s)-1]};return s}
// Bounded static HTML extraction, not an HTML5 browser parser. Unsupported
// markup is explicitly rejected rather than claiming complete web coverage.
func extract(raw string)(title,text string,links []string,noindex,nofollow bool,err error){
 d:=xml.NewDecoder(strings.NewReader("<swypik-root>"+scripts.ReplaceAllString(raw," ")+"</swypik-root>"));d.Strict=false;d.AutoClose=xml.HTMLAutoClose;d.Entity=xml.HTMLEntity;var words []string;inTitle:=false;links=[]string{}
 for{t,e:=d.Token();if e==io.EOF{break};if e!=nil{return "","",nil,false,false,e};switch v:=t.(type){case xml.StartElement:name:=strings.ToLower(v.Name.Local);if name=="title"{inTitle=true};attrs:=map[string]string{};for _,a:=range v.Attr{attrs[strings.ToLower(a.Name.Local)]=a.Value};if name=="a"&&attrs["href"]!=""&&len(links)<128&&!strings.Contains(strings.ToLower(attrs["rel"]),"nofollow"){links=append(links,attrs["href"])};if name=="meta"&&(strings.EqualFold(attrs["name"],"robots")||strings.EqualFold(attrs["name"],"swypikbot")){content:=strings.ToLower(attrs["content"]);noindex=noindex||strings.Contains(content,"noindex")||strings.Contains(content,"none");nofollow=nofollow||strings.Contains(content,"nofollow")||strings.Contains(content,"none")};case xml.EndElement:if strings.EqualFold(v.Name.Local,"title"){inTitle=false};case xml.CharData:s:=strings.TrimSpace(string(v));if inTitle{title+=" "+s};if s!=""{words=append(words,s)}}};return strings.TrimSpace(title),strings.Join(strings.Fields(strings.Join(words," "))," "),links,noindex,nofollow,nil
}
type rule struct{path string;allow bool}
type robots struct{rules []rule}
func parseRobots(raw string)robots{
 type group struct{agents []string;rules []rule};groups:=[]group{};g:=group{};flush:=func(){if len(g.agents)>0{groups=append(groups,g)};g=group{}}
 for _,line:=range strings.Split(raw,"\n"){line=strings.TrimSpace(strings.SplitN(line,"#",2)[0]);pair:=strings.SplitN(line,":",2);if len(pair)!=2{continue};k,v:=strings.ToLower(strings.TrimSpace(pair[0])),strings.TrimSpace(pair[1]);switch k{case "user-agent":if len(g.rules)>0{flush()};g.agents=append(g.agents,strings.ToLower(v));case "allow","disallow":if len(g.agents)>0&&v!=""{g.rules=append(g.rules,rule{v,k=="allow"})}}};flush();best:=0;result:=robots{};for _,g:=range groups{specificity:=0;for _,a:=range g.agents{if a=="*"&&specificity<1{specificity=1};if a=="swypikbot"{specificity=10}};if specificity==0||specificity<best{continue};if specificity>best{best=specificity;result.rules=nil};result.rules=append(result.rules,g.rules...)};return result
}
func(r robots)allowed(path string)bool{allowed,best:=true,-1;for _,rule:=range r.rules{pattern:=regexp.QuoteMeta(rule.path);pattern=strings.ReplaceAll(pattern,`\*`,".*");if strings.HasSuffix(pattern,`\$`){pattern=strings.TrimSuffix(pattern,`\$`)+"$"};ok,_:=regexp.MatchString("^"+pattern,path);if !ok{continue};n:=len(strings.ReplaceAll(strings.TrimSuffix(rule.path,"$"),"*",""));if n>best||n==best&&rule.allow{best=n;allowed=rule.allow}};return allowed}
